version: '3.8'
services:
  test-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_auth_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_pgdata: 