name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt 
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --all --release
      - name: Run tests
        run: cargo test --all --release -- --nocapture
      - name: Lint (clippy)
        run: cargo clippy --all -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Install tarpaulin (for coverage)
        run: |
          cargo install cargo-tarpaulin || true
      - name: Run code coverage
        run: cargo tarpaulin --out Xml --all --release --fail-under 90
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./tarpaulin-report.xml
        continue-on-error: true 