name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://test_user:test_pass@localhost:5433/test_auth_db

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --all --release

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_auth_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install sqlx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Wait for database
        run: |
          until pg_isready -h localhost -p 5433 -U test_user -d test_auth_db; do
            echo "Waiting for database..."
            sleep 2
          done
      - name: Run migrations
        run: |
          echo "Running database migrations..."
          sqlx migrate run --database-url $DATABASE_URL
          echo "Migrations completed successfully"
      - name: Verify database setup
        run: |
          echo "Verifying database setup..."
          psql $DATABASE_URL -c "\dt" || echo "Failed to list tables"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM users;" || echo "Failed to query users"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM roles;" || echo "Failed to query roles"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM permissions;" || echo "Failed to query permissions"
      - name: Run database connectivity test
        run: cargo test test_database_connectivity -- --nocapture
      - name: Run tests
        run: cargo test --all --release -- --nocapture

  test-with-db:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_auth_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install sqlx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Wait for database
        run: |
          until pg_isready -h localhost -p 5433 -U test_user -d test_auth_db; do
            echo "Waiting for database..."
            sleep 2
          done
      - name: Run migrations
        run: |
          echo "Running database migrations..."
          sqlx migrate run --database-url $DATABASE_URL
          echo "Migrations completed successfully"
      - name: Verify database setup
        run: |
          echo "Verifying database setup..."
          psql $DATABASE_URL -c "\dt" || echo "Failed to list tables"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM users;" || echo "Failed to query users"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM roles;" || echo "Failed to query roles"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM permissions;" || echo "Failed to query permissions"
      - name: Run database connectivity test
        run: cargo test test_database_connectivity -- --nocapture
      - name: Run tests with database
        run: cargo test --all --release -- --nocapture

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint (clippy)
        run: cargo clippy --all -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check formatting
        run: cargo fmt --all -- --check

  coverage:
    runs-on: ubuntu-latest
    needs: [test, test-with-db]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_auth_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install sqlx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Install tarpaulin (for coverage)
        run: |
          cargo install cargo-tarpaulin || true
      - name: Wait for database
        run: |
          until pg_isready -h localhost -p 5433 -U test_user -d test_auth_db; do
            echo "Waiting for database..."
            sleep 2
          done
      - name: Run migrations
        run: |
          echo "Running database migrations..."
          sqlx migrate run --database-url $DATABASE_URL
          echo "Migrations completed successfully"
      - name: Verify database setup
        run: |
          echo "Verifying database setup..."
          psql $DATABASE_URL -c "\dt" || echo "Failed to list tables"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM users;" || echo "Failed to query users"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM roles;" || echo "Failed to query roles"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM permissions;" || echo "Failed to query permissions"
      - name: Run code coverage with database
        run: cargo tarpaulin --out Xml --all --release --fail-under 60
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./tarpaulin-report.xml
        continue-on-error: true

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [test, test-with-db, coverage]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_auth_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install sqlx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Install tarpaulin
        run: |
          cargo install cargo-tarpaulin || true
      - name: Wait for database
        run: |
          until pg_isready -h localhost -p 5433 -U test_user -d test_auth_db; do
            echo "Waiting for database..."
            sleep 2
          done
      - name: Run migrations
        run: |
          echo "Running database migrations..."
          sqlx migrate run --database-url $DATABASE_URL
          echo "Migrations completed successfully"
      - name: Verify database setup
        run: |
          echo "Verifying database setup..."
          psql $DATABASE_URL -c "\dt" || echo "Failed to list tables"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM users;" || echo "Failed to query users"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM roles;" || echo "Failed to query roles"
          psql $DATABASE_URL -c "SELECT COUNT(*) FROM permissions;" || echo "Failed to query permissions"
      - name: Run tests with coverage for SonarCloud
        run: |
          cargo tarpaulin --out Xml --all --release
          mkdir -p target/sonar
          cp tarpaulin-report.xml target/sonar/cobertura.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 